fun main() {
    println("Set")
    val alergenos = setOf("mani", "lactosa", "gluten", "mani", "lactosa", "huevos")
    println("alergenos set: ${alergenos}")
    println("Operaciones de conjuntos")
    val alergenosComunes = setOf("mani", "lactosa", "gluten", "nueces")
    val intolerancias = setOf("lactosa", "gluten", "fructosa")
    println("alergenosComunes set: ${alergenosComunes}")
    println("intolerancias set: ${intolerancias}")
    println("union: ${alergenosComunes union intolerancias}")
    println("interseccion: ${alergenosComunes intersect intolerancias}")
    println("substraccion: ${alergenosComunes subtract intolerancias}")
    println("alergenosComunes set: ${alergenosComunes}")
    println("intolerancias set: ${intolerancias}")

    println("Set Mutable")
    val restriccionesAlimentarias = mutableSetOf("vegetariano", "vegano", "sin gluten")
    println(restriccionesAlimentarias)
    restriccionesAlimentarias.add("vegetariano")
    restriccionesAlimentarias.add("bajo en sodio")
    restriccionesAlimentarias.remove("vegano")
    println("Verificar si elemento existe ${"vegetariano" in restriccionesAlimentarias}")
    println("Verificar si elemento existe ${"vegano" in restriccionesAlimentarias}")
}